services:
  demo:
  kml:
  tms:
  wmts:
  wms:
    srs: ['EPSG:3857', 'EPSG:900913', 'EPSG:4258', 'EPSG:4326', 'EPSG:25831']
    image_formats: ['image/jpeg', 'image/png']
    md:
      # metadata used in capabilities documents
      title: Taller MapProxy
      abstract: Ejercicio de aceleración de WMS y OSM con MapProxy
      online_resource: http://localhost:8080/service
      contact:
        person: Pedro-Juan Ferrer, Iván Sánchez y Jorge Sanz
        position: Facilitadores
        organization: Geoinquietos Valencia
        email: pferrer@osgeo.org , jsanz@osgeo.org y ivan@sanchezortega.es
      access_constraints:
        Este servicio tiene únicamente objetivos educativos.
      fees: 'None'

layers:
  - name: compuesta
    title: Parkings sobre ortofoto
    layers:
      - name: orto5m-icc
        title: Ortofoto 1:5000 del ICC de la zona de Girona
        sources: [icc_cache]
      - name: parkings
        title: Parkings de Girona 
        sources: [parkings_cache]

caches:
  icc_cache:
    grids: [GLOBAL_MERCATOR]
    sources: [icc_wms]
  parkings_cache:
    grids: [parkings]
    sources: []
    cache:
      type: mbtiles
      filename: girona.mbtiles

sources:
  icc_wms:
    type: wms
    req:
      url: http://shagrat.icc.es/lizardtech/iserv/ows
      layers: orto5m
    supported_srs: ['EPSG:4326', 'EPSG:25831']
    coverage:
      bbox: [2.67,41.88,2.97,42.07]
      bbox_srs: 'EPSG:4326'

  osm_tiles_girona:
    type: tile
    url: http://tile.openstreetmap.org/%(tms_path)s.%(format)s
    grid: osm
    coverage:
      bbox: [2.67,41.88,2.97,42.07]
      bbox_srs: 'EPSG:4326'

grids:
  parkings:
    base: GLOBAL_MERCATOR
    num_levels: 17

globals:
  cache:
    base_dir: 'cache_data'
    lock_dir: 'cache_data/locks'

  image:
      resampling_method: bilinear
      jpeg_quality: 90
